build:
  script:
    - python3 txtmerge.py locations glife.txt
    - ./txt2gam.linux glife.txt glife.qsp
  artifacts:
    name: "glife-dev-${CI_BUILD_ID}"
    paths: ['glife.qsp']
    expire_in: 1 week